
classDiagram
    class Valor {
        +boolean estado
        +Valor(boolean estado)
        +evaluar() boolean
    }

    class Compuerta {
        +String tipo
        +Valor entrada1
        +Valor entrada2
        +Compuerta(String tipo, Valor e1, Valor e2)
        +Compuerta(String tipo, Valor e1)
        +evaluar() boolean
    }

    Compuerta "1" --> "1..2" Valor : usa como entrada